### ISSUE TITLE
rattletrap-6.2.3-windows.exe: not enough bytes

### ISSUE THREAD

**Issue by Gurch1** [tfausak/rattletrap#110]
Trying to change the map on a replay
--
Converted a .replay file to JSON
Find+Replace from
TrainStation_Dawn_P.TheWorld:PersistentLevel
to
beach_P.TheWorld:PersistentLevel

> rattletrap-6.2.3-windows.exe --mode encode < output.json > newreplayfile.replay
**rattletrap-6.2.3-windows.exe: not enough bytes**

this creates a file called newreplayfile.replay containing nothing.

**Comment by tfausak** [comment]
Weird! This might be related to #73. If possible, can you upload the original replay file?

**Comment by Gurch1** [comment]
Attached Original, Edited replay file and JSON file

[replay files.zip](https://github.com/tfausak/rattletrap/files/2953960/replay.files.zip)

**Comment by tfausak** [comment]
Unfortunately I wasn't able to replicate this. I downloaded your replay and ran the following commands:

``` sh
stack exec -- rattletrap -i original.replay |
  sed 's/TrainStation_Dawn_P.TheWorld:PersistentLevel/beach_P.TheWorld:PersistentLevel/' |
  stack exec -- rattletrap -m encode -o modified.replay
```

That generated a modified replay file without issue. Is it possible that some part of the find and replace process went wrong? Or maybe this is a problem with piping the files around on Windows. Can you try re-running the command using `--input output.json` and `--output newreplayfile.replay` instead of `< output.json` and `> newreplayfile.replay` respectively?

**Comment by tfausak** [comment]
I'm closing this for now. I think the fix is to use `--input` (or -`i`) and `--output` (or `-o`) rather than redirecting or using pipes. If that doesn't work for you, please re-open this and I'd be happy to continue investigating.

**Comment by harshitvyas98** [comment]
hey i am trying to conver an unreal replay file to json, but it showing the error "user error(not enough bytes)" , can you please help thank you

**Comment by tfausak** [comment]
Can you open a new issue for that and upload the replay you're trying to parse?

**Comment by harshitvyas98** [comment]
Hey Thanks for responseI have initiated a new issue this is the link :https://github.com/tfausak/rattletrap/issues/228   Thank youFrom: Taylor FausakSent: Friday, March 12, 2021 11:40 AMTo: tfausak/rattletrapCc: harshitvyas98; CommentSubject: Re: [tfausak/rattletrap] rattletrap-6.2.3-windows.exe: not enough bytes (#110) Can you open a new issue for that and upload the replay you're trying to parse?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
