### ISSUE TITLE
How do I replace player name

### ISSUE THREAD

**Issue by daftpenguin** [tfausak/rattletrap#154]
[652E81534E51A51B8AC711A023024BBB.zip](https://github.com/tfausak/rattletrap/files/4216376/652E81534E51A51B8AC711A023024BBB.zip)

I am attempting to change my display name in this replay from "no chat | left goes" to "Daft Penguin".

When I replace all instances, playback works fine, but the game crashes when I seek (sometimes the first seek works). If I instead pad the replacement with spaces so that it is the same length, the replay works fine, so I imagine I need to update some length or offset values.

I noticed that the "PlayerName" objects within the header have a size that appears to be 5+number of characters in string (consistent with 2 other replays). Adjusting the size, or padding only the PlayerName str's, does not fix the problem. Furthermore, adjusting the size and padding the other replacements does not work either.

I'm thinking I need to adjust the stream_size and size in content body, and at least the size of the arrays containing my PlayerName, but I cannot tell how exactly to compute these values and if this is all that is needed.

At this point, I am blindly hacking around, so any help with this would be appreciated.

**Comment by tfausak** [comment]
I'm surprised that simply changing the name doesn't work. It's been a while since I've actually messed around with any replay files. I think the `stream_size` is only used to pad things out with zeros. As long as your new name is shorter (which it is) then the stream size shouldn't cause problems.

Looking through the JSON output of your replay, I see your name pop up in a few places.

``` json
{
  "id": {
    "limit": 106,
    "value": 34
  },
  "name": "Engine.PlayerReplicationInfo:PlayerName",
  "value": {
    "string": "no chat | left goes"
  }
}
```

This is with all your player replication info. Changing the name here should work fine. Behind the scenes, strings are prefixed with their length. Rattletrap takes care of that though. 

``` json
{
  "name": "no chat | left goes",
  "number": {
    "limit": 7,
    "value": 1
  },
  "unique_id": {
    "local_id": 0,
    "remote_id": {
      "steam": "76561198828548670"
    },
    "system_id": 1
  },
  "unknown1": true,
  "unknown2": true,
  "unknown3": 0
}
```

This is part of your game replication info. Same story here.

``` json
{
  "kind": "StrProperty",
  "size": "24",
  "value": {
    "str": "no chat | left goes"
  }
},
```

This shape shows up in the header a few times. If you change this one, be sure to change the "size" as well. This isn't handled automatically by Rattletrap because the size kind of belongs to the outer wrapper; it tells you how many bytes to allocate for the thing inside.

---

After looking at that, I remembered that the replay content has a `key_frames` field. Key frames are places where everything is replicated. (Normal frames only replicate things that have changed.) Since you mentioned the game only crashes when you seek, it's likely that changing your name changes the length some of the frames, which put the key frames in different places. Each key frame has a bit offset. Computing new offsets would be challenging.

``` json
{
  "frame": 278,
  "position": 207204,
  "time": 17.115631
}
```

The good news is that key frames aren't really necessary for playing back replays. Assuming things haven't changed since the last time I tried, I think you can simply remove all the key frames and everything should Just Work ™️. 

Can you try setting `content.body.key_frames` to `[]` and see what happens? You JSON should end up looking something like this:

``` js
{
  "content": {
    "body": {
      "key_frames": [],
      // ...
    },
    // ...
  },
  // ...
}
```

If that doesn't work you may want to also try keeping only the first key frame (the one with `"position": 0`).

**Comment by daftpenguin** [comment]
Thanks for a quick and detailed response.

Removing all of the key frames did not work, but keeping the first frame did.

I was hoping to be able to modify replays in which my display name was shorter than what I am modifying it to, otherwise simply appending whitespace would have been sufficient.

However, with all but the first key frame removed, I simply calculated the number of total characters added to the replication info (number of instances * additional characters added per instance), and added this value to the stream_size and size values. I've only tested this with two replays so far, but it seems to be working fine.

Thanks for all your help. :)

**Comment by tfausak** [comment]
I'm glad you got it working! 

Weird that modifying the `stream_size` and `size` values is necessary. But whatever works! 

Be aware that names with fancy characters take twice as much storage as plain names. Since `Daft Penguin` is all ASCII it only needs 12 bytes. But if you wanted to use something like `Ðaft Ƥenguin` you would need 24 bytes. You can see all the specifics in the [`getTextSize`](https://github.com/tfausak/rattletrap/blob/60ee694e6fc5e2186ff716b12c360ee7b91a394a/source/library/Rattletrap/Encode/Str.hs#L36) function.

**Comment by ZagozYT** [comment]
Perfect! I was working at changing different parts of the ...\Body too. Thank you.
