### ISSUE TITLE
How to convert psynet byte array to number string

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#155]
For playstation, you convert the byte array to a long.  I was wondering, how this is accomplished?  Some replay files do not have a header and therefore, to get a players unique ID, it has to be found in the network data which contains the byte array as their unique ID.  I am curious how this is done so that I may replicate this functionality in my codebase if a replay file does not have a header. 
I found this part:
`decodeStr :: Decode Str
decodeStr = do
  rawSize <- decodeInt32le
  bytes <- getByteString (normalizeTextSize rawSize)
  pure (Str (dropNull (getTextDecoder rawSize bytes)))`

 I'm  not a Haskell coder by any means so any help would be greatly appreciated.  Thanks!!

**Comment by tfausak** [comment]
Sure! Let me see if I can help. But before I start, I want you to know that there are parsers written in other languages that you may be more familiar with. In particular C# (https://github.com/jjbott/RocketLeagueReplayParser) and Rust (https://github.com/nickbabcock/rrrocket). 

You question mentions a lot of terms, some of which are at odds with each other.

- "PsyNet" is Psyonix's thing, which is different than PlayStation. I'm assuming you're talking about PlayStation. 
- PlayStation IDs have both text (the name) and an array of numbers (the unique ID, I think). Since you mention `decodeStr`, I'm assuming you're talking about the text. 

So I think you're asking how Rattletrap parses PlayStation names in the network stream. That's what I'll answer. If that's not right, please let me know! 

This all starts with the `RemoteId` type, which is unsurprisingly used for all the remote IDs like PlayStation and Xbox. 

https://github.com/tfausak/rattletrap/blob/60ee694e6fc5e2186ff716b12c360ee7b91a394a/source/library/Rattletrap/Type/RemoteId.hs#L11-L12

There's nothing terribly interesting in the type, so let's turn our attention to the decoder, which is responsible for parsing the network stream.

https://github.com/tfausak/rattletrap/blob/60ee694e6fc5e2186ff716b12c360ee7b91a394a/source/library/Rattletrap/Decode/RemoteId.hs#L22

Based on my above assumptions, I think `decodePsName` is the function you're interested in. 

https://github.com/tfausak/rattletrap/blob/60ee694e6fc5e2186ff716b12c360ee7b91a394a/source/library/Rattletrap/Decode/RemoteId.hs#L32-L35

You said you're not familiar with Haskell, so here's a (hopefully) understandable description of that chunk of code:

1. `getByteStringBits`: Get 16 bytes worth of bits from the network stream. That comes out to 16*8=128 bits.
2. `reverseBytes`: For each byte that we just got, flip the bits around. If the bits were numbered 01234567 at first, now they're numbered 76543210. 
3. `decodeLatin1`: Interpret those bits as [Latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) encoded text. This might be the crux of what you're after -- I'm not sure. 
4. `dropWhileEnd`: Drop all the null bytes (`0x00`) from the end of the text. We have to do this because PS names always use 16 bytes even if the name is only, say, 5 bytes long. 

Hope that helps!

**Comment by DangerIsGo** [comment]
Thank you for your response.  I'm actually looking at decoding the unique ID (the array of bytes thats printed in a network stream to which you decoded to a long in the header a few months ago..I request I believe I posted).  How does this change what you wrote above?  Here's an example:
`[38,172,174,206,14,206,44,0,128,0,0,0,0,0,0,0,11,94,248,15,233,200,7,106]`
gets converted into
6260025025334573776
Thank you!

**Comment by tfausak** [comment]
Ah, you're asking about the ID part, not the name part. You did indeed open an issue about that before 😄 #124 

I don't have any insight into those values. According to https://github.com/tfausak/rattletrap/issues/124#issuecomment-497514488: "Last 8 bytes of a playstation id is the online-id". This might come in handy too: https://github.com/tfausak/rattletrap/issues/144#issuecomment-547497062

**Comment by DangerIsGo** [comment]
That's what I was looking for!  Thank you very much :)
