### ISSUE TITLE
Editing Repetition (JSON file)

### ISSUE THREAD

**Issue by ZagozYT** [tfausak/rattletrap#241]
Hi, I'm kind of new in this.
I'm trying to edit some stuff in a repetition, and I discovered that if you dont edit "stream_size" correctly at "Content\Body", it wont work properly or even the game will not open the repetition. So I was wondering if there is any way (program, code, etc) that calculates that number instead of having to calculate it by your self. I hope so, Thanks.

Here is an Example:
![Example](https://user-images.githubusercontent.com/87614600/126076182-445481bf-ca12-4150-b54e-c548ba126e42.jpg)

**Comment by ZagozYT** [comment]
Oooops, I read some of the clossed Issues. Resolver my problem.

**Comment by tfausak** [comment]
I saw your comment over here: https://github.com/tfausak/rattletrap/issues/154#issuecomment-882257627. I'm glad that issue helped! 

Also for the stream size, Rattletrap will make sure the value is big enough to hold the actual stream data. It doesn't shrink the value automatically, which is why it's still in the JSON representation. I would like to get rid of the stream size entirely, but I wasn't able to figure it out in #175.
