### ISSUE TITLE
I cant open RattleTrap

### ISSUE THREAD

**Issue by WaterWite** [tfausak/rattletrap#260]
When I try to open rattletrap it gives me these errors.
![unknown-1](https://user-images.githubusercontent.com/104832090/166439400-dc194dad-bd2a-4c89-8a0f-4a79952b19d5.png)
![unknown](https://user-images.githubusercontent.com/104832090/166439404-2db076c0-ddcd-48f6-b75e-08135a70f18a.png)

**Comment by WaterWite** [comment]
I have also tried adding these dlls to my computer

**Comment by tfausak** [comment]
Thanks for reporting this! Sorry that Rattletrap isn't working for you. I have a couple questions that might help me diagnose the problem here:

- Where did you download Rattletrap from? I'm guessing [the release page](https://github.com/tfausak/rattletrap/releases/tag/11.2.6), but perhaps you got it somewhere else. 
- Which version of Windows are you using? I've successfully used Rattletrap on Windows 10.

**Comment by WaterWite** [comment]
> 
yes i got from the release page and im using win 10 version 10.0.19043 Build 19043.
Ive tried installing all the missing dlls and have so successfully but now i have an error which says i just cant launch the program.
![image](https://user-images.githubusercontent.com/104832090/167160902-31cb1851-7391-4790-ad7f-c614a9808ba0.png)

**Comment by WaterWite** [comment]
also when  i try to run a previous version the it works but no results when i type in a command

**Comment by tfausak** [comment]
I was able to reproduce the problem with both Rattletrap 11.2.6 and 11.2.5. But version [11.2.4](https://github.com/tfausak/rattletrap/releases/tag/11.2.4) worked fine for me. I'd suggest using that version in the meantime. 

The fact that 11.2.4 works but 11.2.5 doesn't suggests this is caused by #255, which upgraded from GHC 9.0 to 9.2. 

After looking around, I found this upstream bug in GHC: https://gitlab.haskell.org/ghc/ghc/-/issues/21196#note_413833. That suggests downgrading to GHC 9.2.1 could fix this problem while we await GHC 9.2.3.

**Comment by WaterWite** [comment]
i tried that but it still doesnt work ;-;

**Comment by WaterWite** [comment]
ill try to run it on a vm to see if it works if not do you have a discord?

**Comment by WaterWite** [comment]
nope doesnt work in vm either

**Comment by tfausak** [comment]
When you say that older versions don't work, what do you mean? Do you get the DLL error that you reported for the latest version, or does something else happen? 

``` powershell
PS C:\Users\Taylor\Downloads> .\rattletrap-11.2.4-windows.exe --version
11.2.4

PS C:\Users\Taylor\Downloads> .\rattletrap-11.2.6-windows.exe --version
# nothing happens
```

Rattletrap is a command-line application, so double-clicking on the executable doesn't really do anything. To actually parse a replay you'd have to run something like `./rattletrap-11.2.4-windows.exe --input example.replay --output replay.example` in a command prompt.

**Comment by tfausak** [comment]
Weird, version 11.2.7 doesn't work for me:

![image](https://user-images.githubusercontent.com/408753/167297516-d495ed6a-810e-4386-a1cc-343a142012f4.png)

Perhaps this was caused by upgrading from `windows-2019` to `windows-latest`, which is `windows-2022`.
https://github.com/tfausak/rattletrap/commit/9371913e9b0e6af621f9adba49f9d27550350303#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL39
https://github.com/actions/virtual-environments/tree/54dc44b7a26d417e128f380927d78e2093e470d3#available-environments

**Comment by WaterWite** [comment]
sorry i was away.  i will try this immediately

**Comment by tfausak** [comment]
No problem! There isn't anything for you to try. I have a Windows machine to test with. I haven't been able to get anything to work yet.

**Comment by tfausak** [comment]
Can you give version 11.2.9 a try? It worked for me. https://github.com/tfausak/rattletrap/releases/tag/11.2.9
