### ISSUE TITLE
Doesn't seem to install on windows

### ISSUE THREAD

**Issue by markduk** [tfausak/rattletrap#266]
Hi, I tried running rattletrap-11.2.9-windows.exe, it opened a console window and then didn't do anything, no errors.  I can type in the console.  I tried `rattletrap --help` but that didn't do anything.
What is the expected behaviour?
Thanks

I'm on Windows 10

**Comment by markduk** [comment]
Worked it out, I needed to rename the exe to rattletrap.exe then I can use it from the command line.

**Comment by tfausak** [comment]
I'm glad that you got it working! I'm going to leave this issue open because I think I can improve the user experience for this. In particular I can check [`hIsTerminalDevice `](https://hackage.haskell.org/package/base-4.16.1.0/docs/System-IO.html#v:hIsTerminalDevice) and display a message to the user. That should help in cases where someone double-clicks on `rattletrap.exe` in the file explorer, or if they run `./rattletrap` without any input from the command line.
