### ISSUE TITLE
Information on value ranges and bias

### ISSUE THREAD

**Issue by jeromepl** [tfausak/rattletrap#49]
I am looking to create a binary file from a bunch of replays and, in order to minimize space, would like to allocate as few bytes as possible for each value of `rigid_body_state_attribute_value`s.

Could you provide some information on the range of these values: location, rotation (although this one seems to always be 0 - 65536 which is exactly a 2 bytes unsigned integer), linear_velocity and angular_velocity?

Just from playing around, I have a feeling most of these could be stored in 2 bytes, but that might be stretching it, especially for linear_velocity values.

Also, the bias value seems like it could be of some use to make sure all values are positive, but I haven't been able to find any information on it anywhere.

Any help would be appreciated!

**Comment by tfausak** [comment]
Unfortunately I don't have any special insight into these values. The [`RigidBodyStateAttribute`](https://hackage.haskell.org/package/rattletrap-3.0.0/docs/Rattletrap-Attribute-RigidBodyState.html) docs list all the fields and their types. To give a little commentary on each one:

- Sleeping: This is stored as a single bit. Not going to do much better than that.

- Location: Stored as four compressed words, which are a pretty fundamental data type in the replays. Just in case you're not familiar, a compressed word has a maximum size (which is known ahead of time) and fits its value into either N or N-1 bits depending on the value and the max size. For example, let's say that the max size is 4 (0b100). The value we want to store is 3 (0b011). Instead of writing all three bits, we can only write the first two (0b11) because the third bit has to be 0. If it was 1, the whole value (0b111) would be 7, which would be over the max size.

- Rotation: Stored as three compressed words.

- Linear and angular velocity: Not stored if the actor is sleeping. Otherwise stored like the location. 

In general, the data in the replays is copied from the network stream. I assume Epic and Psyonix have done their best to make it as compact as possible. However, depending on what exactly you're trying to do, you might be able to do better. A couple ideas:

- Dump the replays as minified JSON, cram them all together in a tarball, and compress it. The JSON that Rattletrap spits out compresses extremely well. If I remember correctly, a single replay in a `.json.gz` is about the same size as the original `.replay`. I suspect that multiple replays will compress very well, potentially ending up smaller than the replay binaries.

- Remove unnecessary stuff from the replays. 

  - Do you need every property in the header? Probably not.

  - Key frames, messages, and marks aren't necessary.

  - Since the replay is made from the network stream, it contains redundant data. Every key frame (approximately every 10 seconds) replicates every attribute for every actor. Most of that hasn't changed, but the server sends it anyway to make sure everything is in sync. You can potentially save a lot of space by removing unnecessary replications. This is a little complicated, but the basic idea is to start at the beginning of the replay, keep track of the current state of everything, and only keep replications that actually changed anything. See [`optimizeFrames`](https://github.com/tfausak/octane/blob/0.20.3/library/Octane/Utility/Optimizer.hs#L21) in Octane for a (probably confusing) example of this. 

I hope that helps! It would be useful for me to know what you're trying to achieve and why the resulting binary replay file needs to be small.

**Comment by jeromepl** [comment]
To give more information: I am trying to create a dataset mapping player and ball positions to controller inputs. The goal is to then use this dataset to train some neural networks!
I am currently using rattletrap to decode replay files to json. I then parse that json to get only the values I need and output them to a binary file. Since I will be parsing a lot of replays, I would like this binary file to be as small as possible.
I am thus trying to find the minimum number of bytes to allocate to store a single [`RigidBodyStateAttribute`](https://hackage.haskell.org/package/rattletrap-3.0.0/docs/Rattletrap-Primitive-Vector.html#t:Vector).

Thank you for the explanation on compressed words! You say that a compressed word has a maximum size **which is known ahead of time**. If I could get a hold of this value, I could use it to figure out the number of bytes to allocate for each vector component. I feel like there is a relationship between this max value and the [bias](https://github.com/tfausak/rattletrap/blob/d82be43af21b44a8b7c862bb6c5a7aea42766c81/library/Rattletrap/Primitive/Vector.hs#L23) (or limit on [line 18](https://github.com/tfausak/rattletrap/blob/d82be43af21b44a8b7c862bb6c5a7aea42766c81/library/Rattletrap/Primitive/Vector.hs#L18)?), but can't figure it out from the code (I have never touched Haskell before, and I think the code I linked here has hardcoded values for bit indices).

**Comment by tfausak** [comment]
Yeah, in general the maximum value of a compressed word is known ahead of time. For the `Vector` type, only the maximum value of the `bitSize` is known; it's 19. So it can be any integral value between 0 and 19 inclusive. Each delta component (`dx`, `dy`, and `dz`) can be any integral value between 0 and `2 ^ (bitSize + 2)`. In other words, between `2 ^ 2` (4) and `2 ^ 21` (2,097,152). 

If you're trying to save every bit, compressed JSON just isn't going to cut it. Using the `338173964F9F71EBDD31058A1936CBB4` replay as an example, here are some file sizes:

Description | Size
--- | ---
Original binary replay | 1.5 MB
Minified, compressed JSON | 2.2 MB
Compressed JSON | 3.7 MB
Minified JSON | 31 MB
JSON | 159 MB

Even putting a bunch of JSON replays into a tarball and compressing them doesn't help. Everything in the `replays/` directory is 12 MB as a compressed tarball of binary files and 22 MB as a compressed tarball of JSON files.

I still think the best bet is removing redundant or unnecessary information from the replays.

**Comment by tfausak** [comment]
I wrote a little JavaScript utility to strip unnecessary information from replays. It saved about 10% (from 1.5 MB to 1.3 MB) off the `338173964F9F71EBDD31058A1936CBB4` replay. https://gist.github.com/tfausak/4cb555d7164c689b99ff0d422107a182

If you are only interested in player and ball positions, you could modify the script to only keep `TAGame.RBActor_TA:ReplicatedRBState` attributes. You could also completely truncate the header and the non-frame content. The resulting replay wouldn't be usable by Rocket League, but Rattletrap could still parse it.

**Comment by jeromepl** [comment]
Sorry if I wasn't clear: I am not using rattletrap to re-encode the replays after I strip unnecessary information! I am simply outputting the values I need to a new binary file in a format of my choosing. This does not necessarily ensures that the new binary file is smaller than the original replay file (especially since I am not compressing words), but it does make it simpler when it comes to reading the values off of it to feed into a neural network or any other type of machine learning algorithm!

**Comment by tfausak** [comment]
Oh, gotcha! That certainly makes things easier 😄 

I think I've told you all I know about vectors and compressed words in Rattletrap. Anything else I can help with?

**Comment by jeromepl** [comment]
I think I have all the information I need, thank you very much for all the help!

Considering that dx, dy and dz (and thus x, y, z) have a maximum of 2^21, I can safely store these in 3 bytes!
