### ISSUE TITLE
Rattletrap fails to parse new replay format from 8/29 update

### ISSUE THREAD

**Issue by Sciguymjm** [tfausak/rattletrap#91]
New replays: https://drive.google.com/drive/folders/1d3T9iBFUFXpHI8XJsu4JW8dxtPt-sNvQ?usp=sharing

Returns code 1.

Error: `rattletrap-5.0.1-linux: don't know how to get attribute value Str {strValue = 
 TAGame.PRI_TA:SpectatorShortcut"}`

**Comment by dtracers** [comment]
Clubs are listed in replays btw.

It replaces team name it seems and it has an extra thing next to their name

**Comment by dtracers** [comment]
https://cdn.discordapp.com/attachments/412423088521740288/484418004357087232/D91AF66748CF1600F9695C9D997AE10F.replay

Here is a replay with club names
The team name is STRAW HAT PIRATES
and the tag is SHP
I am guessing that this is probably related to the error

**Comment by tfausak** [comment]
Thanks for the report! I probably won't get a chance to look at this for a day or two. I would happily accept a PR adding this attribute value, which should be easy if it's one of the currently known types. #86 is a good example of that type of PR. 

@Sciguymjm: Here's your replay. I re-uploaded it to make sure it's always available for this repository. Thanks for recording such a small replay! [A67618BF482676140B627B999BA9F038.replay.zip](https://github.com/tfausak/rattletrap/files/2333179/A67618BF482676140B627B999BA9F038.replay.zip)

@dtracers: Here's your replay. I wouldn't put it into the test suite as-is because it's so big. Is it possible to record a smaller replay that exhibits the same problem? [D91AF66748CF1600F9695C9D997AE10F.replay.zip](https://github.com/tfausak/rattletrap/files/2333198/D91AF66748CF1600F9695C9D997AE10F.replay.zip)

**Comment by andrewchae** [comment]
Don't think that issue has to do with club stuff. We already have these fields in rattletrap:

```
  , ("TAGame.Team_TA:ClubColors", AttributeTypeClubColors)
  , ("TAGame.Team_TA:CustomTeamName", AttributeTypeString)
  , ("TAGame.Team_TA:GameEvent", AttributeTypeFlaggedInt)
  , ("TAGame.Team_TA:LogoData", AttributeTypeFlaggedInt)
```

If anyone wants to help try to figure this out let's get a group together.

**Comment by enzanki-ars** [comment]
Adding `("TAGame.PRI_TA:SpectatorShortcut", AttributeTypeString)` to the `rawAttributeTypes` got closer, but still some issues.  Still working on it.  

```
### Error in:   54:"a676: patch 1.50 - test 1"
could not get name for index Word32le {word32leValue = 65536}
### Error in:   66:"d91a: patch 1.50 - test 2"
don't know how to get attribute value Str {strValue = "Engine.Actor:bCollideWorld"}
```

**Comment by tfausak** [comment]
Nice!

For the first error, 65,536 is 2^16, so that seems pretty likely to be wrong. For the second one, any attribute like `Scope.Class:bField` is a boolean value, but sometimes the real problem is that the thing right before that was decoded improperly. 

Annoyingly, figuring this stuff out can be really tedious. Normally I wait for @jjbott to figure it out and copy him 😬

**Comment by tfausak** [comment]
It might be worth taking a look at these changes 😉 
https://github.com/jjbott/RocketLeagueReplayParser/compare/620773652a328a510a273b4dc36fac2026be57f7...2339e2e0a32b6dc2be06d78d0acb2797a7260a44

**Comment by enzanki-ars** [comment]
I think I figured out why the other two do not parse. 

If you look at https://github.com/jjbott/RocketLeagueReplayParser/blob/2339e2e0a32b6dc2be06d78d0acb2797a7260a44/RocketLeagueReplayParser/NetworkStream/ProductAttribute.cs#L30, whien `licenseeVersion >= 23`, then there are four bytes of info that rattletrap does not seem to have any code for, so I assume that is continues parsing 4 bytes off for the rest of the replay.
